### ISSUE TITLE
Random observations

### ISSUE THREAD

**Issue by pudo** [alephdata/alephclient#1]
* Really like the `api` class. 
* Why are we using ":" for path sep? It doesn't make a difference technically, but "/" might be more intuitive? I also wouldn't slugify the foreign_ids, since slugify can have different results based on the version of PyICU/unidecode that's installed. Unicode is OK for foreign_ids. 
* You really do need to set a foreign_id for each file, otherwise they will be duplicated if their SHA changes. 
* I'd add file_name [here](https://github.com/alephdata/alephclient/blob/master/alephclient/tasks/crawldir.py#L43) for all uploads.

**Comment by pudo** [comment]
* The click options for host and api_key should also have an envvar equivalent, ALEPH_HOST and ALEPH_API_KEY?

**Comment by sunu** [comment]
All of it should be addressed by https://github.com/alephdata/alephclient/commit/7c889046509dce86d5d1734c8727b78cf34fbcd2
